"""init student platform

Revision ID: 1d43214b7c9c
Revises: 8f0279139432
Create Date: 2026-02-07 14:46:26.939989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d43214b7c9c'
down_revision: Union[str, None] = '8f0279139432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_courses_course_id_fkey', 'student_courses', type_='foreignkey')
    op.drop_constraint('student_courses_student_id_fkey', 'student_courses', type_='foreignkey')
    op.create_foreign_key(None, 'student_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_courses', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_courses', type_='foreignkey')
    op.drop_constraint(None, 'student_courses', type_='foreignkey')
    op.create_foreign_key('student_courses_student_id_fkey', 'student_courses', 'students', ['student_id'], ['id'])
    op.create_foreign_key('student_courses_course_id_fkey', 'student_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
