"""init student platform

Revision ID: 8f0279139432
Revises: 9d9eb7083a88
Create Date: 2026-02-07 14:42:53.501539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0279139432'
down_revision: Union[str, None] = '9d9eb7083a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degrees', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'degrees', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'degrees', type_='foreignkey')
    op.drop_column('degrees', 'student_id')
    # ### end Alembic commands ###
